@startuml ServicioNotificaciones.puml
skinparam classAttributeIconSize 0

package "Servicio de Notificaciones" {

    enum MedioContacto {
        EMAIL
        SMS
        WHATSAPP
    }

    class GestorNotificaciones {
        + procesarEvento(evento: TipoEvento, idDestinatario: UUID, parametros: Map)
        + despacharNotificacion(n: Notificacion)
    }

    enum TipoEvento {
        INACTIVIDAD_DONANTE
        DONACION_ASIGNADA_ENTIDAD
        DONACION_ASIGNADA_DONANTE
        MISION_CUMPLIDA
        CAMBIO_CATEGORIA
    }

    class Evento{
        - RolDestinatario: List<Rol>
        - Descripcion: String
        - TipoEvento: TipoEvento
        + ValidoParaNotificar(Rol): boolean
    }

    note left of Evento
    La idea seria
    tener eventos 
    ya definidos 
    en el sistema
    endnote

    class NotificacionFabric{
        + crearNotificacion()
    }

    class Notificacion {
        - id: UUID
        - Destinatario: Persona
        - mensaje: String
        - evento: Evento
        - fechaCreacion: LocalDateTime
        - fechaEnvio: LocalDateTime
        - enviada: boolean
        + marcarComoCompletada()
    }

    interface NotificadorAdapter {
        + enviar(n: Notificacion): boolean
    }

    class AdaptadorEmail implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a SMTP/SendGrid"
    }

    class AdaptadorSMS implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a Twilio"
    }

    class AdaptadorWhatsApp implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a Meta API"
    }

    class CreadorMensajesTemplate {
        + generarCuerpoMensaje(evento: TipoEvento, parametros: Map): String
    }

    ' Relaciones
    
    GestorNotificaciones --> NotificadorAdapter : delega envío a >
    GestorNotificaciones --> CreadorMensajesTemplate : utiliza para armar texto >
    GestorNotificaciones ..> NotificacionFabric : usa >

    NotificacionFabric --> Notificacion

    Notificacion --> MedioContacto : a través de >
    Notificacion --> Evento : originada por >

    Evento --> TipoEvento : corresponde a >

}
@enduml