@startuml ServicioLogistica.puml
skinparam classAttributeIconSize 0

package "Servicio de Logística y Depósito" {

    enum EstadoRuta {
        PLANIFICADA
        EN_CURSO
        FINALIZADA
    }

    class GestorLogisticaYDeposito {
        + registrarCamion(patente: String, modelo: String)
        + ingresarDonacionADeposito(idDonacion: UUID)
        + planificarRuta(fecha: LocalDate, patenteCamion: String, idDonaciones: List<UUID>)
        + iniciarRuta(idRuta: UUID)
        + actualizarUbicacionCamion(patente: String, lat: Double, lon: Double)
    }

    class Deposito {
        - id: UUID
        - nombre: String
        - direccion: Direccion
        - capacidadMaxima: Integer
        - idDonacionesDisponibles: List<UUID>
        + registrarIngreso(idDonacion: UUID)
        + registrarSalida(idDonacion: UUID)
        + auditarVencidos()
    }

    class Camion {
        - patente: String
        - modelo: String
        - ubicacionActual: Coordenada
        - ultimaActualizacion: LocalDateTime
        - activo: boolean
        + actualizarUbicacion(c: Coordenada)
    }

    class RutaEntrega {
        - id: UUID
        - fechaPlanificada: LocalDate
        - fechaInicioReal: LocalDateTime
        - estado: EstadoRuta
        - donacionesAsignadas: List<UUID>
        - camionAsignado: Camion
        - depositoOrigen: Deposito
        + iniciarRecorrido()
        + finalizarRecorrido()
    }

    class Coordenada {
        - latitud: Double
        - longitud: Double
    }
    
    class Direccion {
        - calle: String
        - altura: String
        - localidad: String
    }

    ' Relaciones
    GestorLogisticaYDeposito "1" *-- "0..*" Camion : administra >
    GestorLogisticaYDeposito "1" *-- "0..*" RutaEntrega : planifica y monitorea >
    GestorLogisticaYDeposito "1" *-- "1" Deposito : gestiona >
    
    RutaEntrega --> EstadoRuta : se encuentra en >
    RutaEntrega "1" --> "1" Camion : ejecutada por >
    RutaEntrega "0..*" --> "1" Deposito : parte desde >
    
    Camion "1" *-- "1" Coordenada : rastreado en >
    Deposito "1" *-- "1" Direccion : ubicado en >

}
@enduml