server.port=8002
spring.cloud.compatibility-verifier.enabled=false
spring.application.name=donatrack-logistica
management.endpoint.health.show-details=always

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:donatrack}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:donatrack}
