@startuml DonaTrack_CasosDeUso
left to right direction
skinparam packageStyle rectangle

actor "Usuario Público" as Publico
actor "Persona Donante" as Donante
actor "Beneficiario" as Entidad
actor "Persona Administradora" as Admin

package "DonaTrack - Sistema de Gestión de Donaciones" {
    
    ' --- Casos de Uso de Multiple individuos ---
    usecase "Registrarse Persona" as UC_Registro
    usecase "Iniciar Sesión" as UC_Login

    ' --- Casos de Uso de Acceso ---
    usecase "Ver landing page" as UC_Publico1

    ' --- Casos de Uso de Persona Donante ---
    usecase "Filtrar donaciones realizadas" as UC_D1
    usecase "Navegar entidades beneficiarias" as UC_D2
    usecase "Consultar misiones e insignias" as UC_D3
    usecase "Seguir entregas activas en mapa" as UC_SeguirMapa

    ' --- Casos de Uso de Beneficiario ---
    usecase "Registrar necesidad" as UC_E1
    usecase "Visualizar Donaciones Asignadas" as UC_E2
    usecase "Confirmar Donación" as UC_E3
    usecase "Cargar Fotos" as UC_E4

    ' --- Casos de Uso de Persona Administradora ---
    usecase "Registrar recepción de donación" as UC_A2
    usecase "Actualizar donaciones" as UC_A3
    usecase "Asignar donación" as UC_A4
    usecase "Administrar camiones" as UC_A5
    usecase "Visualizar ranking" as UC_A6
    usecase "Importar CSV" as UC_A7
}

' --- Relaciones del Usuario Público ---
Publico --> UC_Publico1
Publico --> UC_Registro
Publico --> UC_Login

' --- Relaciones de Persona Donante ---
Donante --> UC_Login
Donante --> UC_D1
Donante --> UC_D2
Donante --> UC_D3
Donante --> UC_SeguirMapa
Donante --> UC_Registro

' --- Relaciones de Beneficiario ---
Entidad --> UC_Login
Entidad --> UC_E1
Entidad --> UC_E2
Entidad --> UC_E3
Entidad --> UC_SeguirMapa
Entidad --> UC_Registro

' Relación de extensión para subir fotos opcionales/comprobantes
UC_E3 <.. UC_E4 : <<extend>>
UC_A2 <.. UC_Registro : <<extend>>

' --- Relaciones de Persona Administradora ---
Admin --> UC_Login
Admin --> UC_A2
Admin --> UC_A3
Admin --> UC_A4
Admin --> UC_A5
Admin --> UC_A6
Admin --> UC_A7

@enduml