@startuml DonaTrack_ServicioDonaciones_CasosDeUso
left to right direction
skinparam packageStyle rectangle

actor "Usuario Público" as Publico
actor "Persona Donante" as Donante
actor "Beneficiario" as Entidad
actor "Persona Administradora" as Admin

package "Microservicio de Gestión de Donaciones" {
    
    ' --- Casos de Uso Generales ---
    usecase "Registrarse en la plataforma" as UC_Registro
    usecase "Iniciar Sesión" as UC_Login
    usecase "Ver landing page" as UC_Publico1

    ' --- Casos de Uso de Persona Donante ---
    usecase "Filtrar donaciones realizadas" as UC_D1
    usecase "Navegar entidades beneficiarias" as UC_D2

    ' --- Casos de Uso de Beneficiario ---
    usecase "Registrar necesidad material" as UC_E1
    usecase "Visualizar donaciones asignadas" as UC_E2
    usecase "Confirmar recepción de entrega" as UC_E3
    usecase "Cargar fotos de recepción" as UC_E4

    ' --- Casos de Uso de Persona Administradora (en el Depósito) ---
    usecase "Registrar donación original (carga única)" as UC_A2
    usecase "Actualizar estado de donaciones vencidas" as UC_A3
    usecase "Confirmar destino final de donación (Matchmaking)" as UC_A4
    usecase "Ejecutar algoritmos de asignación a demanda" as UC_A4_2
    usecase "Importar donantes masivos mediante CSV" as UC_A7
}

' --- Relaciones del Usuario Público ---
Publico --> UC_Publico1
Publico --> UC_Registro
Publico --> UC_Login

' --- Relaciones de Persona Donante ---
Donante --> UC_Login
Donante --> UC_D1
Donante --> UC_D2

' --- Relaciones de Beneficiario ---
Entidad --> UC_Login
Entidad --> UC_E1
Entidad --> UC_E2
Entidad --> UC_E3

' Relaciones de inclusión y extensión
UC_E3 <.. UC_E4 : <<include>>
UC_A2 <.. UC_Registro : <<extend>>

' --- Relaciones de Persona Administradora ---
Admin --> UC_Login
Admin --> UC_A2
Admin --> UC_A3
Admin --> UC_A4
Admin --> UC_A4_2
Admin --> UC_A7

@endif
@enduml