@startuml DonaTrack-Diagrama-Clases.puml
skinparam classAttributeIconSize 0
skinparam linetype ortho

package ConexionPorFuera{
    class ConeccionIngresoInicial{}
}

package "servicio de donaciones"{
    package "Gestión de Personas" {
        enum TipoDocumento {
            DNI
            CUIT
            PASAPORTE
        }

        class DocumentoIdentidad {
            - tipo: TipoDocumento
            - numero: String
        }

        DocumentoIdentidad --> TipoDocumento

        enum TipoPersonaJuridica {
            GUBERNAMENTAL
            ONG
            EMPRESA
            INSTITUCION
        }

        enum MedioContacto {
            CORREO
            TELEFONO
            WHATSAPP
        }

        abstract class Persona {
            - id: UUID
            - email: String
            - contacto: Contacto
            - direccion: Direccion
            - documento: DocumentoIdentidad
            - roles: List<Rol>
            + agregarRol(Rol r)
            + validarRol(Rol r)
            + validarDocumentacion(DocumentoIdentidad d)
            + setDocumento(DocumentoIdentidad documento)
            + actualizarInformacion(Map<String, Object> datosNuevos)
        }

        class Contacto {
            - correoElectronico: String
            - telefono: String
            - whatsapp: String
            - medioPredeterminado: MedioContacto
        }

        class Direccion {
            - calle: String
            - altura: Decimal
            - localidad: String
            - pais: Pais
            - codigoPostal: String
            - coordenadas: Coordenada
        }

        class Coordenada {
            - latitud: Decimal
            - longitud: Decimal
        }

        class Provincia{
            - nombreProvincia: String
            - Pais: Pais
        }

        class Pais {
            - nombrePais: String
            - nacionalidad: String
        }

        class PersonaHumana extends Persona {
            - nombre: String
            - apellido: String
            - edad: int
            + validarRol(r: Rol)
            + validarDocumentacion(DocumentoIdentidad d)
            + actualizarInformacion(Map<String, Object> datosNuevos)
        }

        note top of PersonaHumana
        **Regla de negocio:**
        Tira excepción de invalidez de 
        rol si el rol es EntidadBeneficiaria 
        (acepta solo Donante,
        Representante o Administrador)
        end note

        class PersonaJuridica extends Persona {
            - razonSocial: String
            - tipo: TipoPersonaJuridica
            - representantes: List<Representante>
            - rubro: String
            + agregarRepresentante(Representante r)
            + validarRol(Rol r)
            + validarDocumentacion(DocumentoIdentidad d)
            + actualizarInformacion(Map<String, Object> datosNuevos)
        }

        note top of PersonaJuridica
        **Regla de negocio:**
        Tira excepción de 
        invalidez de rol si el rol es 
        Representante o Administrador
        end note

        'relaciones
        Direccion --> Provincia : "es de un"
        Provincia --> Pais : "forma parte de"
        Direccion --> Coordenada : "se encuentra"
        Persona --> Direccion : "tiene"
        Persona "1" *-- "1" Contacto : "tiene"
        Contacto --> MedioContacto : "define"
        Persona --> DocumentoIdentidad : "tiene"
        PersonaJuridica --> TipoPersonaJuridica : "se clasifica en"
    }

    package "Gestion de Roles" {
        abstract class Rol {
            - fechaAlta: LocalDate
        }

        class Donante extends Rol {
            - donacionesRealizadas: List<Donacion>
            - historialRecepciones: List<RecepcionDonacion>
            + agregarDonacion(Donacion d)
            + agregarRecepcion(RecepcionDonacion r)
            + consultarEstadoDonacion(Donacion d)
            + filtrarDonaciones(estado: EstadoDonacion, categoria: String)
            + UbicacionCamion()
        }

        class Representante extends Rol {
            - cargo: String
            - organizacion: PersonaJuridica
        }

        class EntidadBeneficiaria extends Rol {
            - donacionesAsignadas: List<Donacion>
            - necesidadesDeclaradas: List<Necesidad>
            - correoRepresentante: String
            + registrarNecesidad(n: Necesidad)
            + confirmarRecepcion(d: Donacion, fotos: List<String>)
            + EstadoDonaciones()
            + UbicacionCamion()
        }

        class Administrador extends Rol {
            - estrategiaAsignacion: AsignacionStrategy
            - estrategiaImportador: ImportadorStrategy
            + importarDonantesMasivos(String rutaArchivo)
            + obtenerRecomendacionAsignacion(List<Donacion> donacionesDisponibles, List<Necesidad> necesidadesDeclaradas)
            + asociarDonacion(d: Donacion, p: Persona)
            + actualizarDonacionesVencidas()
            + asignarDonacionFinal(d: Donacion, e: EntidadBeneficiaria)
            + administrarCamiones()
            + RankingMensual()
        }

        class CorreoRegistro {
            - Destinatario: String
            - mensaje: String
            - fechaEnvio: Date
        }

        interface AsignacionStrategy {
            + recomendarNecesidades(donaciones, necesidades)
        }

        class PorPrioridad
        class PorCercania

        interface ImportadorStrategy {
            + importar(Archivo)
        }

        class ImportadorCSV

        Administrador --> ImportadorStrategy
        Administrador --> AsignacionStrategy
        PorPrioridad ..up|> AsignacionStrategy
        PorCercania ..up|> AsignacionStrategy
        ImportadorCSV ..up|> ImportadorStrategy
        Administrador --> CorreoRegistro : "genera"
    }

    package "Gestion de Ingreso y Segmentación" {
        class RecepcionDonacion {
            - id: UUID
            - fechaRecepcion: Date
            - donante: Donante
            - donacionesSegmentadas: List<Donacion>
            - registradoPor: Administrador
            + segmentarBienes(bienesBrutos)
        }

        class SegmentadorDeBienes {
            - bienesBrutos : List<Bien>
            - estrategiasSegmentacion : List<estrategiaSegmentacion>
            - donacionesResultantes : List<Donacion>
            + procesar(bienesBrutos)
        }

        note left of SegmentadorDeBienes 
        *Regla de negocio:*
        A partir de la "carga única" 
        de bienes, se generan las 
        Donaciones independientes.
        end note

        note left of RecepcionDonacion 
        **Regla de negocio:**
        Representa la "única carga" 
        física en el depósito. A partir 
        de los bienes, se generan las 
        Donaciones independientes.
        end note

        class Donacion {
            - id: UUID
            - fechaCreacion: Date
            - estado: EstadoDonacion
            - bienes: List<Bien>
            - categoria: Categoria
        }

    package Estado{
        enum EstadoDonacionEnum {
            PENDIENTE
            ASIGNADA
            ENTREGADA
            EN_DEPOSITO
            VENCIDA
        }

        abstract class EstadoDonacion{
            + asignar(Beneficiario beneficiario)
            + planificarRuta()
            + iniciarTraslado()
            + entregar()
            + fallarEntrega(String justificacion)
            + marcarVencida()
            + recibirEnDeposito()
        }

        class Asignada implements EstadoDonacion{
            + planificarRuta()
            + EstadoDonacionEnum getValorEnum()
        }

        class Endeposito implements EstadoDonacion{
            + asignar(Beneficiario beneficiario)
            + marcarVencida()
            + getValorEnum()
        }

        class EnTraslado implements EstadoDonacion{
            + entregar()
            + fallarEntrega(String justificacion)
            + getValorEnum()
        }

        class EntregaFallida implements EstadoDonacion{
            + recibirEnDeposito()
            + getValorEnum()
        }

        class Entregada implements EstadoDonacion{
            + getValorEnum()
        }

        class ListaParaEntregar implements EstadoDonacion{
            + iniciarTraslado()
            + getValorEnum()
        }

        class Vencida implements EstadoDonacion{
            + getValorEnum()
        }

        class HistorialEstado {
            - Donacion: Donacion
            - estado: EstadoDonacion
            - fecha: Date
            - observacion: String
            - usuario: Administrador
        }
    }

        class Bien {
            - descripcion: String
            - cantidad: double
            - unidadMedicion: String
            - esUsado: boolean
            - fechaVencimiento: LocalDate
            - foto: List<Foto>
        }

        class Categoria {
            - nombre: String
            - descripcion: String
            - subcategorias: List<Categoria>
            + agregarSubcategoria(categoria)
            + esSubcategoriaDe(categoria)
        }

        class Foto{
            - descripcion: String
            - Url: String
        }

        Bien --> Categoria
        Bien --> Foto
        Categoria --> Categoria

        Donacion *-- HistorialEstado
        Donacion "1" *-- "1..*" Bien : "agrupa"
        Donacion --> EstadoDonacionEnum : "se encuentra en"
        Donacion --> EstadoDonacion : "se encuentra en"

        RecepcionDonacion --> Donante

        SegmentadorDeBienes *-- Donacion : segmenta >
    }

    package "Gestion de Necesidades" {
        enum EstadoNecesidad {
            ABIERTA
            SATISFECHA
        }

        abstract class Necesidad {
            - descripcion: String
            - estado: EstadoNecesidad
            - subcategoriaRequerida: Categoria
            - id: UUID
            - fechaSolicitud: Date
            + estaCubierta(): Boolean
        }

        class NecesidadRecurrente implements Necesidad {
            - cantidadObjetivo: double
            - periodo: String
        }

        class NecesidadExtraordinaria implements Necesidad {
            - cantidadRequerida: double
            + acumularDonacionesParciales()
        }

        Necesidad --> EstadoNecesidad : "se encuentra en"
    }
}

package "Servicio de Incentivos" {
    enum CategoriaDonanteEnum {
        COLABORADOR
        SOSTENEDOR
        TRANSFORMADOR
    }

    abstract class CategoriaDonanteState{
        - perfil: PerfilIncentivos
        + avanzarCategoria()
        + getValorEnum()
    }

    class ColaboradorState implements CategoriaDonanteState{
        + avanzarCategoria()
        + getValorEnum()
    }

    class SostenedorState implements CategoriaDonanteState{
        + avanzarCategoria()
        + getValorEnum()
    }

    class TransformadorState implements CategoriaDonanteState{
        + avanzarCategoria()
        + getValorEnum()
    }

    class GestorIncentivos {
        - PerfilesIncentivos: List<PerfilIncentivos>
        + procesarNuevaDonacion(idDonante: UUID, d: DonacionDTO)
        + ejecutarRankingMensual()
    }

    class PerfilIncentivos {
        - idPerfil: UUID
        - categoriaActual: CategoriaDonante
        - InsigniasObtenidas: List<Insignia>
        + evaluarMisiones(d: DonacionDTO)
        + subirCategoria()
        + agregarInsignia(i: Insignia)
        + visibilizarInsignia(i: Insignia, visible: boolean)
    }

    class MetricasDonante {
        - totalDonaciones: int
        - organizacionesAyudadas: int
        - impactoAcumulado: double
        + registrarDonacion(d: DonacionDTO)
        + generarGraficoEvolucionMensual()
    }

    abstract class MisionesPorNivel{
        - Misiones: List<Mision>
        - MisionActual: Mision
        - PerfilAsociado: PerfilIncentivos
        - CategoriaObtener: CategoriaDonante
        - FechaAsignacion: LocalDate
        + Clonar()
    }
    
    note top of MisionesPorNivel
    Cada clase concreta de MisionesPorNivel
    Tiene sus Misiones especificas concretas
    end note

    class MisionesPorNivelSostenedor extends MisionesPorNivel{
        + Clonar()
    }

    class MisionesPorNivelTransformador extends MisionesPorNivel{
        + Clonar()
    }

    class MisionesPorNivelColaborador extends MisionesPorNivel{
        + Clonar()
    }

    abstract class Mision {
        - nombre: String
        - descripcion: String
        - progresoObjetivo: int
        - completada: boolean
        + ConsultarProgeso(): int
        + getDistanciaObjetivo(): int
        + PerderProgreso()
    }

    class MisionRacha extends Mision {
        - RachaActual: int
        + ConsultarProgeso(): int
        + PerderProgreso()
    }

    class MisionCompletitud extends Mision {
        + ConsultarProgeso(): int
    }

    class MisionHabilDonador extends Mision {
        - cantidadMinimaBienes: int
        + ConsultarProgeso(): int
    }

    class MisionDonacionesExitosas extends Mision {
        + ConsultarProgeso(): int
    }

    
    Class insigniaFabric{
        +CrearInsignia()
    }


    class Insignia {
        - nombre: String
        - descripcion: String
        - fechaObtencion: LocalDate
        - visiblePublicamente: boolean
        + setVisible(visible: boolean)
    }

    class RankingMensual {
        - Fecha: LocalDate
        - topDonantes: List<PosicionRanking>
        + calcularRanking(perfiles: List<PerfilIncentivos>)
        + obtenerTop3(): List<PosicionRanking>
    }

    class PosicionRanking {
        - PerfilAsociado: PerfilIncentivos
        - posicion: int
        + MisionesCompletadas(): int
    }

    note right of PosicionRanking
    Para determinar las misionesCompletados
    se evalua la cantidad de insignias obtenidas
    end note

    ' Relaciones
    GestorIncentivos --> RankingMensual : genera >
    GestorIncentivos --> PerfilIncentivos : administra >

    MisionesPorNivel *-- Mision : contine >
    MisionesPorNivel --> CategoriaDonante : Objetivo >
    MisionesPorNivel <-- PerfilIncentivos : Debe completar <

    Mision ..> insigniaFabric : usa >

    insigniaFabric <-- Insignia

    PerfilIncentivos "1" *-- "1" MetricasDonante : consolida datos en >
    PerfilIncentivos --> CategoriaDonanteEnum : posee >

    PerfilIncentivos --> CategoriaDonanteState

    RankingMensual *-- "0..*" PosicionRanking : contiene >
}

package "Servicio de Notificaciones" {

    enum MedioContacto {
        EMAIL
        SMS
        WHATSAPP
    }

    class GestorNotificaciones {
        + procesarEvento(evento: TipoEvento, idDestinatario: UUID, parametros: Map)
        + despacharNotificacion(n: Notificacion)
    }

    enum TipoEvento {
        INACTIVIDAD_DONANTE
        DONACION_ASIGNADA_ENTIDAD
        DONACION_ASIGNADA_DONANTE
        MISION_CUMPLIDA
        CAMBIO_CATEGORIA
    }

    class Evento{
        - RolDestinatario: List<Rol>
        - Descripcion: String
        - TipoEvento: TipoEvento
        + ValidoParaNotificar(Rol): boolean
    }

    note left of Evento
    La idea seria
    tener eventos 
    ya definidos 
    en el sistema
    endnote

    class NotificacionFabric{
        + crearNotificacion()
    }

    class Notificacion {
        - id: UUID
        - Destinatario: Persona
        - mensaje: String
        - evento: Evento
        - fechaCreacion: LocalDateTime
        - fechaEnvio: LocalDateTime
        - enviada: boolean
        + marcarComoCompletada()
    }

    interface NotificadorAdapter {
        + enviar(n: Notificacion): boolean
    }

    class AdaptadorEmail implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a SMTP/SendGrid"
    }

    class AdaptadorSMS implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a Twilio"
    }

    class AdaptadorWhatsApp implements NotificadorAdapter {
        + enviar(n: Notificacion): boolean
        note "Simula conexión a Meta API"
    }

    class CreadorMensajesTemplate {
        + generarCuerpoMensaje(evento: TipoEvento, parametros: Map): String
    }

    ' Relaciones
    
    GestorNotificaciones --> NotificadorAdapter : delega envío >
    GestorNotificaciones --> CreadorMensajesTemplate : utiliza para armar texto >
    GestorNotificaciones ..> NotificacionFabric : usa >

    NotificacionFabric --> Notificacion

    Notificacion --> MedioContacto : a través de >
    Notificacion --> Evento : originada por >

    Evento --> TipoEvento : corresponde a >


}

' --- CONEXIONES ARQUITECTÓNICAS ENTRE PAQUETES ---

' Gestión de Personas y Roles
Persona "1" *--down--- "1..*" Rol : "asume"

' Conexiones de Dominio (Roles y Donaciones)
EntidadBeneficiaria "1" ---> "0..*" Donacion : "tiene asignadas"
Donante "1" --> "0..*" Donacion : "realiza (asoc. por Admin)"
Donacion -up-> Administrador : "es gestionada por"
RecepcionDonacion --> Administrador
EntidadBeneficiaria "1" *--- "0..*" Necesidad : "declara"
Necesidad "*" ---> "1" Categoria : "demanda"
Necesidad "1" o-- "0..*" Donacion : "tiene"

' Conexiones Servicio de Incentivos y donaciones

class donacionesController {}

Donante <---> donacionesController : "Consulta"
GestorIncentivos ---> donacionesController : "Solicita Donaciones realizadas"

class ActividadDonacionDto{}

Donante --> ActividadDonacionDto
PerfilIncentivos --> ActividadDonacionDto

' Conexiones con el Servicio de Notificaciones
class IncentivosController{}

    'conexion con Donaciones evento de asignación
    Administrador --> IncentivosControler
    'conexion con Donaciones evento inactividad

    'conexion con Donaciones CorreoRegistro
    CorreoRegistro --> IncentivosControler : "despacha vía"

    'conexion con Incentivos evento MisionCumplida
    Mision --> IncentivosControler
    IncentivosControler --> GestorNotificaciones

'conexion exterior
ConeccionIngresoInicial --> SegmentadorDeBienes

@enduml


